apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: django
  template:
    metadata:
      labels:
        pod: django
    spec:
      containers:
        - name: django
          image: waztom/car:latest
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
          - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: SECRET_KEY
            - name: IBM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: IBM_API_KEY
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: DB_NAME
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: POSTGRES_PORT
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: CELERY_RESULT_BACKEND
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: env-credentials
                  key: RABBITMQ_DEFAULT_PASS

            - name: POSTGRES_HOST
              value: postgres-service

            - name: REDIS_HOST
              value: redis-service

            - name: RABBIT_HOST
              value: rabbit-service
