# Example of synthesis recipe 1
[
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {
                "value": "m-tolylphenylamine",
                "quantity": {"value": 1.0, "unit": "mmol"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {
                "value": "dichloromethane",
                "quantity": {"value": 10.0, "unit": "ml"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {
                "value": "3-methoxyphenylacetic acid",
                "quantity": {"value": 1.0, "unit": "mmol"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {
                "value": "1-(3-dimethylaminopropyl)-3-ethylcarbodiimide hydrochloride",
                "quantity": {"value": 1.0, "unit": "mmol"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {
                "value": "DMAP",
                "quantity": {"value": 0.05, "unit": "mmol"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "stir",
        "content": {
            "atmosphere": None,
            "duration": {"value": 86400.0, "quantity": None, "unit": "seconds"},
            "temperature": {"value": 25, "quantity": None, "unit": "celsius"},
            "stirring_speed": {"value": "normal", "quantity": None, "unit": None},
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {"value": "water", "quantity": {"value": 10.0, "unit": "ml"}, "unit": None},
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "extract",
        "content": {
            "repetitions": {"value": 1, "quantity": None, "unit": None},
            "solvent": {
                "value": "ethyl acetate",
                "quantity": {"value": 10.0, "unit": "ml"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "collect-layer",
        "content": {"layer": {"value": "organic", "quantity": None, "unit": None}},
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "wash",
        "content": {
            "material": {"value": "brine", "quantity": {"value": 10.0, "unit": "ml"}, "unit": None},
            "repetitions": {"value": 1, "quantity": None, "unit": None},
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "dry-solution",
        "content": {"material": {"value": "magnesium sulfate", "quantity": None, "unit": None}},
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "concentrate",
        "content": {},
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "purify",
        "content": {},
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "store",
        "content": {
            "sample_name": {
                "value": "COc1cccc(CC(=O)Nc2cccc(-c3ccccc3C)c2)c1",
                "quantity": None,
                "unit": None,
            }
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
]

## Example synthesis recipe 2
[
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {
                "value": "2-methylindolizine",
                "quantity": {"value": 1.0, "unit": "mmol"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {
                "value": "4-fluorobenzoyl chloride",
                "quantity": {"value": 1.0, "unit": "mmol"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "add",
        "content": {
            "atmosphere": None,
            "duration": None,
            "temperature": None,
            "dropwise": {"value": False, "quantity": None, "unit": None},
            "material": {
                "value": "SnCl4",
                "quantity": {"value": 1.0, "unit": "mmol"},
                "unit": None,
            },
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "purify",
        "content": {},
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
    {
        "name": "store",
        "content": {
            "sample_name": {
                "value": "Cc1cc2ccccn2c1C(=O)c1ccc(F)cc1",
                "quantity": None,
                "unit": None,
            }
        },
        "status": "NEW",
        "hasSpectrometerPdf": False,
        "remainingTime": 0,
        "completionPercentage": 0.0,
        "expectedTime": 0,
    },
]
