version: "3.9"

services:
  app:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/code
    command: >
      sh -c "conda run -n CARdeploy python /code/manage.py migrate && 
             conda run -n CARdeploy python /code/manage.py wait-for-db &&
             conda run -n CARdeploy python /code/manage.py makemigrations &&
             conda run -n CARdeploy python /code/manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - frontend
      - rabbit

  db:
    image: postgres:10-alpine
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    restart: always
    build: .
    command: >
      sh -c "cd /code && 
             conda run -n CARdeploy celery -A CAR worker -l info"
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - rabbit

  frontend:
    restart: on-failure
    build: .
    command: >
      sh -c "cd /code && 
             npm run dev"
    volumes:
      - .:/code
      - node_modules:/code/node_modules

  rabbit:
    image: rabbitmq:alpine
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata:
  node_modules:
