common_solvents = {
    "CC(C)=O": "acetone",
    "CC#N": "acetonitrile",
    "c1ccccc1": "benzene",
    "CCCCO": "1-butanol",
    "CCC(C)O": "2-butanol",
    "CCC(C)=O": "2-butanone",
    "CC(C)(C)O": "t-butyl alcohol",
    "ClC(Cl)(Cl)Cl": "carbon tetrachloride",
    "Clc1ccccc1": "chlorobenzene",
    "ClC(Cl)Cl": "chloroform",
    "C1CCCCC1": "cyclohexane",
    "ClCCCl": "1,2-dichloroethane",
    "OCCOCCO": "diethylene glycol",
    "CCOCC": "diethyl ether",
    "COC": "dimethyl ether",
    "COCCOC": "1,2-dimethoxy-ethane",
    "CN(C)C=O": "dimethyl-formamide ",
    "C[S](C)=O": "dimethyl sulfoxide",
    "C1COCCO1": "1,4-dioxane",
    "CCO": "ethanol",
    "CCOC(C)=O": "ethyl acetate",
    "OCCO": "ethylene glycol",
    "OCC(O)CO": "glycerin",
    "CCCCCCC": "heptane",
    "CN(C)[P](=O)(N(C)C)N(C)C": "hexamethylphosphoramide",
    "CN(C)P(N(C)C)N(C)C": "hexamethylphosphoroustriamide",
    "CCCCCC": "hexane",
    "CO": "methanol",
    "COC(C)(C)C": "methyl t-butyl ether",
    "ClCCl": "methylene chloride",
    "CN1CCCC1=O": "N-methyl-2-pyrrolidinone",
    "C[N+]([O-])=O": "nitromethane",
    "CCCCC": "pentane",
    "CCCC(C)C": "isohexane",
    "CCCO": "1-propanol",
    "CC(C)O": "2-propanol",
    "C1CCOC1": "tetrahydrofuran",
    "Cc1ccccc1": "toluene",
    "O": "water",
    "Cc1ccccc1C": "o-xylene",
    "Cc1cccc(C)c1": "m-xylene",
    "Cc1ccc(C)cc1": "p-xylene",
}
