kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 5Gi
