version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/code:cached
      - node_modules:/code/CAR/frontend/node_modules
    env_file:
      - ./.devcontainerenv
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: postgres:10-alpine
    restart: on-failure
    env_file:
      - ./.devcontainerenv
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/code:cached
    env_file:
      - ./.devcontainerenv
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  rabbit:
    image: rabbitmq:alpine
    restart: on-failure
    env_file:
      - ./.devcontainerenv
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata:
  node_modules:
