version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    env_file:
      - ./.env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: postgres:10-alpine
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    env_file:
      - ./.env

  rabbit:
    image: rabbitmq:alpine
    restart: on-failure
    env_file:
      - ./.env

volumes:
  pgdata:
  node_modules:
