# Generated by Django 3.1.3 on 2020-11-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosteps', models.IntegerField(null=True)),
                ('targetmass', models.IntegerField()),
                ('unit', models.CharField(choices=[('mmol', 'Mmol'), ('g', 'G'), ('mg', 'Mg')], default='mg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('productsmiles', models.CharField(db_index=True, max_length=255, null=True)),
                ('productimage', models.FileField(max_length=255, upload_to='productimages/')),
                ('productname', models.CharField(max_length=100, unique=True)),
                ('method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.method')),
            ],
        ),
        migrations.CreateModel(
            name='WashAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('norepetitions', models.IntegerField()),
                ('unit', models.CharField(choices=[('mmol', 'Mmol'), ('ml', 'Ml'), ('mg', 'Mg')], default='ml', max_length=10)),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(db_index=True, max_length=255, null=True)),
                ('image', models.FileField(max_length=255, upload_to='targetimages/')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.project')),
            ],
        ),
        migrations.CreateModel(
            name='StirAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('unit', models.CharField(choices=[('s', 'Seconds'), ('min', 'Minutes'), ('h', 'Hours')], default='min', max_length=10)),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='Reactant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(db_index=True, max_length=255, null=True)),
                ('image', models.FileField(max_length=255, upload_to='reactantimages/')),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.target'),
        ),
        migrations.CreateModel(
            name='MakeSolutionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solute', models.CharField(max_length=100)),
                ('soluteammount', models.IntegerField()),
                ('solvent', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('mol/L', 'Molar'), ('g/L', 'Mass')], default='mol/L', max_length=10)),
                ('concentration', models.IntegerField()),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='DrySolutionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dryingagent', models.CharField(max_length=100)),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='ConcentrateAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentrate', models.BooleanField(default=False)),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('LCMS', 'Lcms'), ('NMR', 'Nmr'), ('XChem', 'Xchem')], default='LCMS', max_length=10)),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='AddAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(null=True)),
                ('unit', models.CharField(choices=[('mmol', 'Mmol'), ('ml', 'Ml'), ('mg', 'Mg')], default='mmol', max_length=10)),
                ('dropwise', models.BooleanField(default=False)),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
    ]
