# Generated by Django 3.1.3 on 2020-11-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosteps', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(db_index=True, max_length=255, null=True)),
                ('image', models.FileField(max_length=255, upload_to='targetimages/')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.project')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workup', models.CharField(choices=[('None', 'Na'), ('HCl', 'Hcl'), ('DCM', 'Dcm')], default='None', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('temperature', models.IntegerField(null=True)),
                ('productsmiles', models.CharField(db_index=True, max_length=255, null=True)),
                ('productimage', models.FileField(max_length=255, upload_to='productimages/')),
                ('productname', models.CharField(max_length=100, unique=True)),
                ('method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.method')),
            ],
        ),
        migrations.CreateModel(
            name='Reactant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvent', models.CharField(choices=[('None', 'Na'), ('DMA', 'Dma'), ('DCM', 'Dcm')], default='None', max_length=10)),
                ('smiles', models.CharField(db_index=True, max_length=255, null=True)),
                ('image', models.FileField(max_length=255, upload_to='reactantimages/')),
                ('moleq', models.IntegerField(null=True)),
                ('addorder', models.IntegerField(null=True)),
                ('concentration', models.IntegerField(null=True)),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.target'),
        ),
    ]
