# Generated by Django 3.1.7 on 2025-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otsession',
            name='visualization_metadata',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
