# Generated by Django 3.1.7 on 2026-02-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_otsession_visualization_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_class', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('intramolecular', models.BooleanField(default=False)),
                ('estimated_yield', models.PositiveIntegerField(blank=True, null=True)),
                ('reaction_smarts', models.JSONField(blank=True, default=list)),
                ('references', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='backend.recipe')),
            ],
            options={
                'ordering': ['reaction_class', 'name', '-version'],
                'unique_together': {('reaction_class', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RecipeActionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField()),
                ('session_type', models.CharField(choices=[('reaction', 'Reaction'), ('stir', 'Stir'), ('workup', 'Workup'), ('workup1', 'Workup1'), ('workup2', 'Workup2'), ('analyse', 'Analyse')], max_length=20)),
                ('driver', models.CharField(choices=[('human', 'Human'), ('robot', 'Robot')], default='robot', max_length=10)),
                ('continuation', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_sessions', to='backend.recipe')),
            ],
            options={
                'ordering': ['session_number'],
                'unique_together': {('recipe', 'session_number')},
            },
        ),
        migrations.RemoveField(
            model_name='column',
            name='type',
        ),
        migrations.RemoveField(
            model_name='otsession',
            name='visualization_metadata',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='type',
        ),
        migrations.RemoveField(
            model_name='well',
            name='type',
        ),
        migrations.AddField(
            model_name='column',
            name='role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='role_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plate',
            name='role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='role_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='well',
            name='role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='role_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='addaction',
            name='calcunit',
            field=models.CharField(choices=[('moleq', 'Moleq'), ('masseq', 'Masseq'), ('uL', 'Ul')], default='moleq', max_length=10),
        ),
        migrations.AlterField(
            model_name='addaction',
            name='volumeunit',
            field=models.CharField(choices=[('uL', 'Ul'), ('mL', 'Ml')], default='uL', max_length=2),
        ),
        migrations.AlterField(
            model_name='extractaction',
            name='bottomlayervolumeunit',
            field=models.CharField(default='uL', max_length=2),
        ),
        migrations.AlterField(
            model_name='extractaction',
            name='volumeunit',
            field=models.CharField(default='uL', max_length=2),
        ),
        migrations.CreateModel(
            name='RecipeStirAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.PositiveIntegerField()),
                ('temperature', models.FloatField(default=25)),
                ('temperature_unit', models.CharField(default='degC', max_length=10)),
                ('duration', models.FloatField()),
                ('duration_unit', models.CharField(default='hours', max_length=10)),
                ('stirring_speed', models.CharField(choices=[('gentle', 'Gentle'), ('normal', 'Normal'), ('vigorous', 'Vigorous')], default='normal', max_length=10)),
                ('plate_role', models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], default='reaction', max_length=20)),
                ('plate_index', models.PositiveIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stir_actions', to='backend.recipeactionsession')),
            ],
            options={
                'ordering': ['action_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipeMixAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.PositiveIntegerField()),
                ('plate_role', models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], default='reaction', max_length=20)),
                ('plate_index', models.PositiveIntegerField(default=1)),
                ('repetitions', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_actions', to='backend.recipeactionsession')),
            ],
            options={
                'ordering': ['action_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipeExtractAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.PositiveIntegerField()),
                ('layer', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=10)),
                ('volume', models.FloatField()),
                ('bottom_layer_volume', models.FloatField(blank=True, null=True)),
                ('smiles', models.CharField(blank=True, max_length=500, null=True)),
                ('solvent', models.CharField(blank=True, max_length=255, null=True)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('from_plate_role', models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], default='reaction', max_length=20)),
                ('from_plate_index', models.PositiveIntegerField(default=1)),
                ('to_plate_role', models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], default='workup', max_length=20)),
                ('to_plate_index', models.PositiveIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extract_actions', to='backend.recipeactionsession')),
            ],
            options={
                'ordering': ['action_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipeAddAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.PositiveIntegerField()),
                ('molecular_context', models.CharField(choices=[('intermolecular', 'Intermolecular'), ('intramolecular', 'Intramolecular')], default='intermolecular', max_length=20)),
                ('material_smarts', models.CharField(blank=True, max_length=500, null=True)),
                ('material_smiles', models.CharField(blank=True, max_length=500, null=True)),
                ('equivalents', models.FloatField()),
                ('quantity_unit', models.CharField(choices=[('moleq', 'Moleq'), ('uL', 'Ul'), ('M', 'Molarity'), ('uM', 'Micromolarity')], default='moleq', max_length=10)),
                ('solvent', models.CharField(blank=True, max_length=255, null=True)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('from_plate_role', models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], default='startingmaterial', max_length=20)),
                ('from_plate_index', models.PositiveIntegerField(default=1)),
                ('to_plate_role', models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')], default='reaction', max_length=20)),
                ('to_plate_index', models.PositiveIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_actions', to='backend.recipeactionsession')),
            ],
            options={
                'ordering': ['action_number'],
            },
        ),
        migrations.AddField(
            model_name='reaction',
            name='recipe_id',
            field=models.ForeignKey(blank=True, help_text='Links to the exact Recipe version used for this reaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='backend.recipe'),
        ),
    ]
