# Generated by Django 3.1.7 on 2026-02-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20260214_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeaddaction',
            name='molecular_context',
            field=models.CharField(blank=True, choices=[('intermolecular', 'Intermolecular'), ('intramolecular', 'Intramolecular')], max_length=20, null=True),
        ),
    ]
