# Generated by Django 3.1.7 on 2026-02-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20260214_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeactionsession',
            name='session_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeaddaction',
            name='action_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeextractaction',
            name='action_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipemixaction',
            name='action_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipestiraction',
            name='action_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
