# Generated by Django 3.1.7 on 2026-02-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20260216_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeaddaction',
            name='quantity_unit',
            field=models.CharField(choices=[('moleq', 'Moleq'), ('masseq', 'Masseq'), ('uL', 'Ul'), ('mL', 'Ml'), ('mg', 'Mg'), ('g', 'G'), ('M', 'Molarity'), ('uM', 'Micromolarity')], default='moleq', max_length=10),
        ),
    ]
