# Generated by Django 3.1.7 on 2026-02-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20260216_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestiraction',
            name='duration_unit',
            field=models.CharField(default='h', max_length=10),
        ),
        migrations.AlterField(
            model_name='stiraction',
            name='durationunit',
            field=models.CharField(choices=[('s', 'Seconds'), ('m', 'Minutes'), ('h', 'Hours')], default='h', max_length=10),
        ),
    ]
