# Generated by Django 3.1.7 on 2026-02-16 23:47

import re
from django.db import migrations, models


def parse_plate_type(raw: str) -> tuple:
    """Parse legacy plate type string into (role, index) tuple.

    Examples:
        'reaction' -> ('reaction', 1)
        'workup1' -> ('workup', 1)
        'workup2' -> ('workup', 2)
        'starting material' -> ('startingmaterial', 1)
    """
    normalised = raw.lower().replace(" ", "").replace("_", "")

    match = re.match(r"^(workup)(\d+)$", normalised)
    if match:
        return match.group(1), int(match.group(2))

    # Single-instance types
    return normalised, 1


def migrate_addaction_data(apps, schema_editor):
    AddAction = apps.get_model('backend', 'AddAction')
    for action in AddAction.objects.all():
        from_role, from_idx = parse_plate_type(action.fromplatetype)
        to_role, to_idx = parse_plate_type(action.toplatetype)
        action.from_plate_role = from_role
        action.from_plate_index = from_idx
        action.to_plate_role = to_role
        action.to_plate_index = to_idx
        action.save()


def migrate_extractaction_data(apps, schema_editor):
    ExtractAction = apps.get_model('backend', 'ExtractAction')
    for action in ExtractAction.objects.all():
        from_role, from_idx = parse_plate_type(action.fromplatetype)
        to_role, to_idx = parse_plate_type(action.toplatetype)
        action.from_plate_role = from_role
        action.from_plate_index = from_idx
        action.to_plate_role = to_role
        action.to_plate_index = to_idx
        action.save()


def migrate_mixaction_data(apps, schema_editor):
    MixAction = apps.get_model('backend', 'MixAction')
    for action in MixAction.objects.all():
        role, idx = parse_plate_type(action.platetype)
        action.plate_role = role
        action.plate_index = idx
        action.save()


def migrate_stiraction_data(apps, schema_editor):
    StirAction = apps.get_model('backend', 'StirAction')
    for action in StirAction.objects.all():
        role, idx = parse_plate_type(action.platetype)
        action.plate_role = role
        action.plate_index = idx
        action.save()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('backend', '0007_update_duration_unit_choices'),
    ]

    operations = [
        # Step 1: Add new fields with defaults
        migrations.AddField(
            model_name='addaction',
            name='from_plate_role',
            field=models.CharField(
                choices=[
                    ('reaction', 'Reaction'), ('workup', 'Workup'),
                    ('spefilter', 'Spefilter'), ('lcms', 'Lcms'),
                    ('xchem', 'Xchem'), ('nmr', 'Nmr'),
                    ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')
                ],
                default='startingmaterial',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='addaction',
            name='from_plate_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addaction',
            name='to_plate_role',
            field=models.CharField(
                choices=[
                    ('reaction', 'Reaction'), ('workup', 'Workup'),
                    ('spefilter', 'Spefilter'), ('lcms', 'Lcms'),
                    ('xchem', 'Xchem'), ('nmr', 'Nmr'),
                    ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')
                ],
                default='reaction',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='addaction',
            name='to_plate_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extractaction',
            name='from_plate_role',
            field=models.CharField(
                choices=[
                    ('reaction', 'Reaction'), ('workup', 'Workup'),
                    ('spefilter', 'Spefilter'), ('lcms', 'Lcms'),
                    ('xchem', 'Xchem'), ('nmr', 'Nmr'),
                    ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')
                ],
                default='reaction',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='extractaction',
            name='from_plate_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extractaction',
            name='to_plate_role',
            field=models.CharField(
                choices=[
                    ('reaction', 'Reaction'), ('workup', 'Workup'),
                    ('spefilter', 'Spefilter'), ('lcms', 'Lcms'),
                    ('xchem', 'Xchem'), ('nmr', 'Nmr'),
                    ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')
                ],
                default='workup',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='extractaction',
            name='to_plate_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mixaction',
            name='plate_role',
            field=models.CharField(
                choices=[
                    ('reaction', 'Reaction'), ('workup', 'Workup'),
                    ('spefilter', 'Spefilter'), ('lcms', 'Lcms'),
                    ('xchem', 'Xchem'), ('nmr', 'Nmr'),
                    ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')
                ],
                default='reaction',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='mixaction',
            name='plate_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stiraction',
            name='plate_role',
            field=models.CharField(
                choices=[
                    ('reaction', 'Reaction'), ('workup', 'Workup'),
                    ('spefilter', 'Spefilter'), ('lcms', 'Lcms'),
                    ('xchem', 'Xchem'), ('nmr', 'Nmr'),
                    ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent')
                ],
                default='reaction',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='stiraction',
            name='plate_index',
            field=models.PositiveIntegerField(default=1),
        ),

        # Step 2: Migrate data from old fields to new fields
        migrations.RunPython(migrate_addaction_data, migrations.RunPython.noop),
        migrations.RunPython(migrate_extractaction_data, migrations.RunPython.noop),
        migrations.RunPython(migrate_mixaction_data, migrations.RunPython.noop),
        migrations.RunPython(migrate_stiraction_data, migrations.RunPython.noop),

        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name='addaction',
            name='fromplatetype',
        ),
        migrations.RemoveField(
            model_name='addaction',
            name='toplatetype',
        ),
        migrations.RemoveField(
            model_name='extractaction',
            name='fromplatetype',
        ),
        migrations.RemoveField(
            model_name='extractaction',
            name='toplatetype',
        ),
        migrations.RemoveField(
            model_name='mixaction',
            name='platetype',
        ),
        migrations.RemoveField(
            model_name='stiraction',
            name='platetype',
        ),
    ]
