# Generated by Django 3.1.7 on 2026-02-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_runtime_actions_use_plate_role_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addaction',
            old_name='from_plate_index',
            new_name='from_plate_role_index',
        ),
        migrations.RenameField(
            model_name='addaction',
            old_name='to_plate_index',
            new_name='to_plate_role_index',
        ),
        migrations.RenameField(
            model_name='extractaction',
            old_name='from_plate_index',
            new_name='from_plate_role_index',
        ),
        migrations.RenameField(
            model_name='extractaction',
            old_name='to_plate_index',
            new_name='to_plate_role_index',
        ),
        migrations.RenameField(
            model_name='recipeaddaction',
            old_name='from_plate_index',
            new_name='from_plate_role_index',
        ),
        migrations.RenameField(
            model_name='recipeaddaction',
            old_name='to_plate_index',
            new_name='to_plate_role_index',
        ),
        migrations.RenameField(
            model_name='recipeextractaction',
            old_name='from_plate_index',
            new_name='from_plate_role_index',
        ),
        migrations.RenameField(
            model_name='recipeextractaction',
            old_name='to_plate_index',
            new_name='to_plate_role_index',
        ),
        migrations.AlterField(
            model_name='addaction',
            name='from_plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='startingmaterial', max_length=20),
        ),
        migrations.AlterField(
            model_name='addaction',
            name='to_plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='reaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='column',
            name='role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extractaction',
            name='from_plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='reaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='extractaction',
            name='to_plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='workup', max_length=20),
        ),
        migrations.AlterField(
            model_name='mixaction',
            name='plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='reaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='plate',
            name='role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipeaddaction',
            name='from_plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='startingmaterial', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeaddaction',
            name='to_plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='reaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeextractaction',
            name='from_plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='reaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeextractaction',
            name='to_plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='workup', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipemixaction',
            name='plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='reaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipestiraction',
            name='plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='reaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='stiraction',
            name='plate_role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], default='reaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='well',
            name='role',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('workup', 'Workup'), ('spefilter', 'Spefilter'), ('lcms', 'Lcms'), ('xchem', 'Xchem'), ('nmr', 'Nmr'), ('startingmaterial', 'Startingmaterial'), ('solvent', 'Solvent'), ('analyse', 'Analyse')], max_length=20, null=True),
        ),
    ]
