# Generated by Django 3.1.7 on 2026-02-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_plate_index_to_role_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mixaction',
            old_name='plate_index',
            new_name='plate_role_index',
        ),
        migrations.RenameField(
            model_name='recipemixaction',
            old_name='plate_index',
            new_name='plate_role_index',
        ),
        migrations.RenameField(
            model_name='recipestiraction',
            old_name='plate_index',
            new_name='plate_role_index',
        ),
        migrations.RenameField(
            model_name='stiraction',
            old_name='plate_index',
            new_name='plate_role_index',
        ),
    ]
