# Generated by Django 3.1.7 on 2026-02-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_stir_mix_plate_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-init_date']},
        ),
    ]
