# Generated by Django 3.1.7 on 2026-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20260220_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='transfer_type',
            field=models.CharField(choices=[('single', 'Single channel'), ('multichannel', 'Multichannel')], default='single', max_length=15),
        ),
    ]
