labware_plates = {
    "4welltrough_4_reservoir_60000ul": {
        "type": ["solvent"],
        "no_wells_in_column": 1,
        "no_wells": 4,
        "no_columns": 4,
        "volume_well": 60000,
        "max_temp": 25,
        "reflux": False,
    },
    # "8welltrough_8_reservoir_25000ul": {
    #     "type": ["solvent"],
    #     "no_wells_in_column": 1,
    #     "no_wells": 8,
    #     "no_columns": 8,
    #     "volume_well": 25000,
    #     "max_temp": 25,
    #     "reflux": False,
    # },
    # "12welltrough_12_reservoir_18000ul": {
    #     "type": ["solvent"],
    #     "no_wells_in_column": 1,
    #     "no_wells": 12,
    #     "no_columns": 12,
    #     "volume_well": 18000,
    #     "max_temp": 25,
    #     "reflux": False,
    # },
    "fluidx_24_vials_2500ul": {
        "type": ["startingmaterial"],
        "no_wells_in_column": 4,
        "no_wells": 24,
        "no_columns": 6,
        "volume_well": 2500,
        "max_temp": 25,
        "reflux": False,
    },
    "fluidx_96_vials_1000ul": {
        "type": ["startingmaterial"],
        "no_wells_in_column": 8,
        "no_wells": 96,
        "no_columns": 12,
        "volume_well": 600,
        "max_temp": 25,
        "reflux": False,
    },
    "labcyte_384_wellplate_100ul": {
        "type": ["xchem", "reaction"],
        "no_wells_in_column": 16,
        "no_wells": 384,
        "no_columns": 24,
        "volume_well": 100,
        "max_temp": 25,
        "reflux": False,
    },
    "labcyte_384_wellplate_12ul": {
        "type": ["xchem", "reaction"],
        "no_wells_in_column": 16,
        "no_wells": 384,
        "no_columns": 24,
        "volume_well": 12,
        "max_temp": 25,
        "reflux": False,
    },
    "plateone_96_wellplate_500ul": {
        "type": ["lcms", "reaction"],
        "no_wells_in_column": 8,
        "no_wells": 96,
        "no_columns": 12,
        "volume_well": 500,
        "max_temp": 25,
        "reflux": False,
    },
    "plateone_96_wellplate_2500ul": {
        "type": ["workup1", "workup2", "workup3", "reaction"],
        "no_wells_in_column": 8,
        "no_wells": 96,
        "no_columns": 12,
        "volume_well": 2500,
        "max_temp": 25,
        "reflux": False,
        "aspirateheightconversion-m": 0.01806,
        "aspirateheightconversion-c": 0.6015,
    },
    "biotage_96_wellplate_2500ul": {
        "type": ["spefilter"],
        "no_wells_in_column": 8,
        "no_wells": 96,
        "no_columns": 12,
        "volume_well": 2500,
        "max_temp": 25,
        "reflux": False,
    },
    "paradox_96_wellplate_961ul": {
        "type": ["reaction"],
        "no_wells_in_column": 8,
        "no_wells": 96,
        "no_columns": 12,
        "volume_well": 961,
        "max_temp": 250,
        "reflux": True,
        "aspirateheightconversion-m": 0.02865,
        "aspirateheightconversion-c": -0.4040,
    },
}
